# Generated by Django 3.2.13 on 2022-06-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='author',
        ),
    ]
